#!/usr/bin/perl -w
# Parse <use> elements in gear_layout.svg and output coordinates for each gear.
#
# We do all the gear layout manually in Inkscape, and at run time we just
# place the gears using this predefined fixed layout.  It's done this way
# because getting gear placement correct is tricky:
#
# - Gears must mesh together at the right distances.
# - Gears must mesh at opposite rotational parity.
# - Due to teeth placement, gears can only mesh at certain angles.
# - Gears should not overlap, except on meshing edges.
#
# It's still possible to generate a placement following the constraints
# above by placing gears one at a time, growing outward from a root gear,
# but this will get us a spanning tree as opposed to some cyclic structure
# that we are able to do with manual placement.
#
# Even if we were able to get a nice automatic placement figured out, we
# still need to do some memory management to make sure the number of gears
# do not grow out of bounds.  All things considered, it was easier and safer
# to go with hardcoded manual placement.

use strict;
use XML::LibXML;

use constant INPUT_LAYER => "gear layout";
use constant CANVAS_SIZE => 1024;

# Add these offsets to the transform attributes to get the true offset.
my %base_offset =
(
   "#Large0" => [9, 9],
   "#Large1" => [137, 9],
   "#Small0" => [34, 162],
   "#Small1" => [162, 162],
);
my %collected_offsets = ();
$collected_offsets{$_} = [] foreach keys %base_offset;

# Load XML from stdin or last argument.
my $dom = XML::LibXML->load_xml(huge => 1, string => (join "", <ARGV>));

# Collect offsets from selected layer.
foreach my $group ($dom->getElementsByTagName("g"))
{
   if( defined $group->{"inkscape:groupmode"} &&
       defined $group->{"inkscape:label"} &&
       $group->{"inkscape:groupmode"} eq "layer" &&
       $group->{"inkscape:label"} eq INPUT_LAYER )
   {
      # Process <use> elements in this layer.
      foreach my $child ($group->childNodes())
      {
         my $name = eval('$child->nodeName');
         next unless defined($name) && $name eq "use";

         unless( defined($child->{"xlink:href"}) &&
                 defined($child->{"transform"}) )
         {
            next;
         }
         my $ref = $child->{"xlink:href"};
         next unless exists $base_offset{$ref};

         if( $child->{"transform"} =~ /^translate\(([-]?\d+),([-]?\d+)\)$/ )
         {
            my $x = $base_offset{$ref}[0] + $1;
            my $y = $base_offset{$ref}[1] + $2;
            push @{$collected_offsets{$ref}}, [$x, $y];
         }
         else
         {
            die "Failed to parse transform: " . $child->{"transform"} . "\n";
         }
      }
   }
}

# Check that there is an equal count of each gear.
my $count = undef;
foreach my $i (keys %collected_offsets)
{
   if( defined($count) )
   {
      if( $count != scalar @{$collected_offsets{$i}} )
      {
         my $error = "Inconsistent counts:\n";
         foreach my $j (keys %collected_offsets)
         {
            $error .= "$j -> " . (scalar @{$collected_offsets{$j}}) . "\n";
         }
         die $error;
      }
   }
   else
   {
      $count = scalar @{$collected_offsets{$i}};
   }
}

# Output collected data.
print "// Generated by $0\n\n",
      "#define GEAR_COUNT $count\n",
      "static const uint16_t kGearLayout[4][$count][2] =\n",
      "{\n";
foreach my $i (sort keys %collected_offsets)
{
   print "\t// $i\n\t{\n";
   foreach my $j (@{$collected_offsets{$i}})
   {
      my @p = @$j;
      if( $p[0] < 0 ) { $p[0] += CANVAS_SIZE; }
      if( $p[1] < 0 ) { $p[1] += CANVAS_SIZE; }
      print "\t\t{$p[0], $p[1]},\n";
   }
   print "\t},\n";
}
print "};\n";
