// Generated by generate_dice.c

#ifndef DICE_DATA_H_
#define DICE_DATA_H_

#include<stdint.h>

#define ROTATION_STEPS 16

// [rx][ry][rz] -> face value
extern const uint8_t kDiceValues[ROTATION_STEPS][ROTATION_STEPS][ROTATION_STEPS];

// [rotate direction][rx][ry][rz] -> {rx, ry, rz}
extern const uint8_t kDiceRotation[ROTATION_STEPS][ROTATION_STEPS][ROTATION_STEPS][ROTATION_STEPS][3];

// [rx][ry][rz] -> {rx, ry, rz}
extern const uint8_t kDiceRotateTowardOrthogonal[ROTATION_STEPS][ROTATION_STEPS][ROTATION_STEPS][3];

// [face value - 1] -> orthogonal configuration count
extern const int kDiceConfigurationCount[6];

// [face value - 1][configuration index] -> {rx, ry, rz}
extern const int kDiceConfigurations[6][12][3];

#endif  // DICE_DATA_H_
