#!/usr/bin/perl -w
# Extract ms_per_tick lines from song definition files.
#
# This is used by special_path.c to make sure that all the timing events are
# in sync with the song definitions.  Inserting and removing measures will
# still require some manual edits in special_path.c, but at least song tempo
# adjustments can be done entirely in the song definition files.

use strict;

if( $#ARGV < 0 )
{
   die "$0 {input.txt|input.m4} [...]\n";
}


# Extract ms_per_tick lines from opened handle.
sub parse_input($)
{
   my ($infile) = @_;

   my @ms_per_tick = ();
   while( my $line = <$infile> )
   {
      # Record definition, removing consecutive entries that define
      # the same ms_per_tick.
      if( $line =~ /^ms_per_tick\s*=\s*(\d+)/ &&
          ($#ms_per_tick < 0 || $1 != $ms_per_tick[$#ms_per_tick]) )
      {
         push @ms_per_tick, $1;
      }
   }
   return @ms_per_tick;
}

# Output definition lines.
sub output_definitions($@)
{
   my ($id, @ms_per_tick) = @_;

   if( $#ms_per_tick < 0 )
   {
      die "Did not find any ms_per_tick lines in $id\n";
   }

   # Output one definition for each ms_per_tick.
   #
   # Note the multi-part naming scheme in the identifiers.  We do this
   # even when the entire song has the same tempo, since most songs
   # will have multiple ms_per_tick lines to increase tick resolution
   # for measures with complicated timing.
   for(my $i = 0; $i <= $#ms_per_tick; $i++)
   {
      print "#define ", uc($id), "_PART", $i + 1, "_MS_PER_TICK ",
            $ms_per_tick[$i], "\n";
   }
   print "\n";
}


print "// Generated by $0\n\n";
foreach my $f (@ARGV)
{
   if( $f =~ /^(?:.*[\/\\])?(\w+)\.txt$/ )
   {
      open my $file, "<$f" or die $!;
      output_definitions($1, parse_input($file));
      close $file;
   }
   elsif( $f =~ /^(?:.*[\/\\])?(\w+)\.m4$/ )
   {
      open my $pipe, "m4 $f|" or die $!;
      output_definitions($1, parse_input($pipe));
      close $pipe;
   }
   else
   {
      die "Unrecognized file type, need .txt or .m4: $f\n";
   }
}
